### PR TITLE
Remove duplicite records in library usage

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
lgtm!

**Review by saisankargochhayat — APPROVED** [review]

**Comment by saisankargochhayat** [comment]
Should close https://github.com/thoth-station/thamos/issues/566 right?

**Comment by saisankargochhayat** [comment]
Do we want to remove the endpoints and still have the methods? Or just remove them?

**Comment by fridex** [comment]
> Should close #566 right?

Nope, this is related to static source code analysis with symbols that is sent to the backend.

**Pull request merged**
