### PR TITLE
Add support for passing options to pip during thamos install

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

```console
thamos install -- --user  # issues pip install --user under the hood.
```

Related-To: #723 

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
Will test this, but it looks like it works.

**Comment by fridex** [comment]
/unhold

@harshad16 PTAL

**Review by harshad16 — APPROVED** [review]
/lgtm

**Pull request merged**
