### PR TITLE
Remove sleep before first attempt to obtain results

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

Fixes: https://github.com/thoth-station/thamos/issues/353

### CODE REVIEW

**Comment by fridex** [comment]
/hold

from time to time I experience https://github.com/thoth-station/thoth-application/issues/568 based on the queueing delay.

**Comment by fridex** [comment]
with https://github.com/thoth-station/thoth-application/issues/568 being fixed and the bugfix propagated with https://github.com/thoth-station/thoth-application/pull/631 we can proceed with this one.

/unhold

**Comment by fridex** [comment]
/hold

... let's wait with this one a bit.

**Comment by fridex** [comment]
/unlock

good to go with recent fixes @KPostOffice @harshad16 :+1:

**Comment by harshad16** [comment]
Thanks @KPostOffice

**Review by harshad16 — APPROVED** [review]
lgtm, lets get this in .

**Pull request merged**
