### PR TITLE
Remove examples/ directory, use thoth-station/cli-examples repo

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

## Description

These examples are no longer maintained, refer to thoth-station/cli-examples repo instead.

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
lgtm! maybe a link in thamos docs to the examples? wdyt?

**Comment by codificat** [comment]
The [readme](https://github.com/thoth-station/thamos/blob/master/README.rst#using-thamos-as-a-cli-tool) already points to cli-examples, so that's fine.

One question though: at first look, the cli-examples repo has less content. Should these be moved (updated?) there?

**Comment by codificat** [comment]
> One question though: at first look, the cli-examples repo has less content. Should these be moved (updated?) there?

Answering to myself: I missed that content in cli-examples is in branches, the readme there explains.




> We can definitely extend cli-examples, but it might be better to pick more real-world problems and show how Thoth solves them.

Fully agree - and that's something to bring in that repo. So, for this one:
/approve
/lgtm

**Comment by fridex** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[codificat](https://github.com/thoth-station/thamos/pull/933#issuecomment-964001037)_, _[pacospace](https://github.com/thoth-station/thamos/pull/933#pullrequestreview-801070427)_

/approve

**Pull request merged**
