### PR TITLE
added diff command and flag

### PR DESCRIPTION
**Pull request by Gkrumbach07**
## Related Issues and Dependencies

- No

## This should yield a new module release

- No

## This Pull Request implements

Added a `diff` command and added a `--diff` flag to `advise` command

### Description

`diff` compares the justifications and stack info of two advises, using the stored previous advise if possible. It only shows the differences and hides the similarities.

### CODE REVIEW

**Review by mayaCostantini — COMMENTED** [review]
lgtm :100: 
When I tested it, the output of the `diff` command contains links to Search UI with a 404 error (https://thoth-station.ninja/search/adviser-220928070754-9305bf8907dd3ffe/summary and https://thoth-station.ninja/search/adviser-220928071551-8a5829084918bfcc/summary), I think they are missing the `/advise` part between `/search` and the analysis ID.

Also, would it be interesting (for later) to support JSON output for diff results?

**Comment by goern** [comment]
+1 on json ;) its all for the machines!

```
PYTHONPATH=. ./thamos-cli version
Thamos Client version: 1.27.11
Thoth API https://khemenu.thoth-station.ninja/api/v1: 0.35.8
```

there seem to be an error in displaying the advise ID, see the missing *a* after the `(`:
```
Try 'adviser-220928133843-a22248989080074f --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Got unexpected extra arguments (v i s e r - 2 2 0 9 2 8 1 3 3 8 4 3 - a 2 2 2 4 8 9 8 9 0 8 0 0 7 4 f)                                                                                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Check Thamos documentation: https://thoth-station.ninja/docs/developers/thamos
```

**Comment by goern** [comment]
```
 PYTHONPATH=../thamos ../thamos/thamos-cli diff adviser-220928134359-bc7c0f22c68aa6b  adviser-220928133843-a22248989080074f  
Comparing old: adviser-220928133843-a22248989080074f to new: adviser-220928134359-bc7c0f22c68aa6b
                                                                                                                   Stack Info Differences                                                                                                                     
                                                                  ╷                                                                                  ╷                                        ╷                                                               
                                                       Difference │ Link                                                                             │ Message                                │ Type                                                          
                                                      ════════════╪══════════════════════════════════════════════════════════════════════════════════╪════════════════════════════════════════╪════════                                                       
                                                       REMOVED    │ https://thoth-station.ninja/search/adviser-220928133843-a22248989080074f/summary │ Results can be browsed in Thoth search │ ✔️ INFO                                                        
                                                       ADDED      │ https://thoth-station.ninja/search/adviser-220928134359-bc7c0f22c68aa6b/summary  │ Results can be browsed in Thoth search │ ✔️ INFO                                                        
                                                                  ╵                                                                                  ╵                                        ╵                                                                                                                                                                                                                                                                                                   
```

/lgtm

**Comment by Gkrumbach07** [comment]
> I think they are missing the /advise part between /search and the analysis ID

I thought this was fixed in an older PR? Are you looking at an older adviser document?

> there seem to be an error in displaying the advise ID, see the missing a after the (:

Was this issue present before this PR?

@mayaCostantini @goern I can add the JSON support, I don't think it will take too much time.

**Comment by mayaCostantini** [comment]
> Are you looking at an older adviser document?

No, both documents (old and new) were generated today.

**Comment by Gkrumbach07** [comment]
> No, both documents (old and new) were generated today.
 
Thats odd. It is updated here: https://github.com/thoth-station/adviser/blob/master/thoth/adviser/boots/thoth_search.py#L37
I am not sure why it still is giving the wrong url

**Review by mayaCostantini — APPROVED** [review]
lgtm, let's force past codeclimate :+1:

**Pull request merged**
