### PR TITLE
Improve error handling when user-api is not available

### PR DESCRIPTION
**Pull request by fridex**
Fixes: #334

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
Should we merge this :rocket:

**Comment by fridex** [comment]
> Should we merge this

It's missing a review. Do you want to review it? :eyes:

**Comment by saisankargochhayat** [comment]
Looks good to be merged :1st_place_medal:

**Comment by fridex** [comment]
> Looks good to be merged

You can hit the "Approved" button and let bots do their job :)

**Pull request merged**
