### PR TITLE
Port to Python 3.8

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
@saisankargochhayat and wishing you a happy new year! :fireworks:

**Review by saisankargochhayat — APPROVED** [review]
Thanks!

**Comment by saisankargochhayat** [comment]
> @saisankargochhayat and wishing you a happy new year! 🎆

@fridex Wish you a very happy new year 🎆

**Pull request merged**
