### PR TITLE
Introduce thamos verify command to check lockfile hash

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/pypa/pipenv/pull/4896

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... let's wait for upstream to see how they want to handle this (to be reasonably compatible).

**Comment by fridex** [comment]
Ready to be reviewed. It looks like upstream is not active in reviewing the PR, but it might be worth having this subcommand available to users.

**Comment by fridex** [comment]
/assign @mayaCostantini

PTAL.

**Comment by mayaCostantini** [comment]
lgtm :100:

**Review by mayaCostantini — APPROVED** [review]

**Pull request merged**
