### PR TITLE
Use runtime_environment_name option in the config file

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

## Description

When generating a config file for Ubuntu 20.04, the runtime environment has `.` in the name which is not valid character in the runtime environment entry. Let's replace any characters that should not occur in the runtime environment entries with dashes. Also, update the version of Fedora in the README example.

### CODE REVIEW

**Review by mayaCostantini — APPROVED** [review]
Thanks 💯 👍🏻 
Just check on mypy and pre-commit and all green

**Comment by fridex** [comment]
All green. Merging.

**Pull request merged**
