### PR TITLE
Introduce thamos index command for listing package indexes available

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
Example output:

```
$ thamos index        
                                     ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓                                      
                                     ┃ URL                                                                         ┃ Verify SSL ┃ Warehouse API url     ┃                                      
                                     ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩                                      
                                     │ https://pypi.org/simple                                                     │ True       │ https://pypi.org/pypi │                                      
                                     │ https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple │ True       │ -                     │                                      
                                     │ https://tensorflow.pypi.thoth-station.ninja/index/rhel7.5/AVX2/simple       │ True       │ -                     │                                      
                                     │ https://tensorflow.pypi.thoth-station.ninja/index/rhel7.6/AVX2/simple       │ True       │ -                     │                                      
                                     │ https://tensorflow.pypi.thoth-station.ninja/index/rhel7.7/AVX2/simple       │ True       │ -                     │                                      
                                     └─────────────────────────────────────────────────────────────────────────────┴────────────┴───────────────────────┘               
```

**Review by pacospace — APPROVED** [review]
lgtm!! 💯

**Pull request merged**
