### PR TITLE
Provide container images sub-command

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/user-api/pull/1506/

## This introduces a breaking change

- [x] Yes

## Description

Provide `thamos images` command instead of `thamos s2i`.

### CODE REVIEW

**Comment by pacospace** [comment]
@fridex PTAL

**Comment by pacospace** [comment]
> /approve

swagger API changes are included in this PR, is it ok? there are other changes made on user-API, should we regenerate it?

**Comment by fridex** [comment]
> > /approve
> 
> swagger API changes are included in this PR, is it ok? there are other changes made on user-API, should we regenerate it? cc @fridex

Yes, these changes should correspond to https://github.com/thoth-station/user-api/pull/1506. The client should be regenerated to reflect that.

**Comment by fridex** [comment]
@pacospace I will test these changes in the test environment on Thursday before this goes to the release (tomorrow is a public holiday).

**Pull request merged**
