### PR TITLE
Fixed wrong exception

### PR DESCRIPTION
**Pull request by saisankargochhayat**
The used ApiException was causing thamos to crash, so we resort to our custom exception. 
Please create a new patch release after merging this.

### CODE REVIEW

**Comment by saisankargochhayat** [comment]
> Does not feel like "service is not available". API exception looks ok-ish to me.
Umm so ApiException is defined by swagger, and it seems to error out on being raised out manually by us.

**Comment by fridex** [comment]
> > Does not feel like "service is not available". API exception looks ok-ish to me.
> 
> Umm so ApiException is defined by swagger, and it seems to error out on being raised out manually by us.

Can we introduce a new exception in that case (if none is applicable for this use case). Also, the message reported could be more descriptive for users of Thamos.

**Comment by saisankargochhayat** [comment]
> > > Does not feel like "service is not available". API exception looks ok-ish to me.
> > 
> > 
> > Umm so ApiException is defined by swagger, and it seems to error out on being raised out manually by us.
> 
> Can we introduce a new exception in that case (if none is applicable for this use case). Also, the message reported could be more descriptive for users of Thamos.

Thank you, will do :)

**Comment by saisankargochhayat** [comment]
@fridex should we merge this?

**Pull request merged**
