### PR TITLE
[WIP] Migrating to Open-API

### PR DESCRIPTION
**Pull request by saisankargochhayat**
It seems after providing the required `swagger-config.json`, the imports in __init__.py are not having the right paths. 
Also, the issue of response type is not solved in open_api

### CODE REVIEW

**Comment by fridex** [comment]
> Also, the issue of response type is not solved in open_api

OK, so let's regenerate the client, and let's implement the waiting logic with `requests` and an explicit check for the HTTP status code on our side.

**Comment by saisankargochhayat** [comment]
> > Also, the issue of response type is not solved in open_api
> 
> OK, so let's regenerate the client, and let's implement the waiting logic with `requests` and an explicit check for the HTTP status code on our side.

Regenerate with an existing swagger right and close this pr?

**Comment by fridex** [comment]
> > > Also, the issue of response type is not solved in open_api
> > 
> > 
> > OK, so let's regenerate the client, and let's implement the waiting logic with `requests` and an explicit check for the HTTP status code on our side.
> 
> Regenerate with an existing swagger right and close this pr?

Yes, sounds good to me :+1:

**Comment by saisankargochhayat** [comment]
Closing in favor of #475

**Pull request closed without merging**
